### ISSUE TITLE
请问这个问题您是如何解决的？

### ISSUE THREAD

**Issue by jackishappy** [Vang-z/HGJO#1]
索引中的冒号运算符的非有限端点或增量。我在添加其他算法的过程中，出现了这个问题。请问您是如何解决的？

**Comment by Vang-z** [comment]
> 这是我的联系方式，[2903602021@qq.com](mailto:2903602021@qq.com) ，求指教，谢谢

有具体的报错信息吗 请精确到报错的代码 谢谢

**Comment by jackishappy** [comment]
***@***.***
 
发件人： Vang-z
发送时间： 2023-06-02 21:17
收件人： Vang-z/HGJO
抄送： jackishappy; Author
主题： Re: [Vang-z/HGJO] 请问这个问题您是如何解决的？ (Issue #1)
***@***.*** ，求指教，谢谢
有具体的报错信息吗 请精确到报错的代码 谢谢
―

**Comment by jackishappy** [comment]
我在求解的过程中，每个粒子的元素会出现NaN编码，可能会出现错误，请问您是如何解决的？



***@***.***
 
发件人： Vang-z
发送时间： 2023-06-02 21:17
收件人： Vang-z/HGJO
抄送： jackishappy; Author
主题： Re: [Vang-z/HGJO] 请问这个问题您是如何解决的？ (Issue #1)
***@***.*** ，求指教，谢谢
有具体的报错信息吗 请精确到报错的代码 谢谢

**Comment by jackishappy** [comment]
索引中的冒号运算符的非有限端点或增量。
出错 OStu（第9行)
fit(j)  = sum(prob(1:x(j,1))) * sum(prob(1:x(j,1))).*sum(prob(1:x(j,1)))/sum(prob(1:x(j,1))) -sum(1:255)
我在求解的过程中粒子中不可避免的出现了NaN，所以会出现问题，请问您看是否是这个问题？请问该如何解决？

**Comment by Vang-z** [comment]
> 

本代码中的`otsu`函数接受的粒子位置参数必须是递增的且值的范围为`0~255`之间的整数。因此，粒子的值如果出现了`Nan`请进一步检查你的算法是如何规范化粒子边界的。
